services:
  openpayments:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: openpayments-dev
    volumes:
      - ./data:/app/data
    working_dir: /app
    command:
      [
        "--dataset","general-payments",
        "--year","2024",
        "--output","s3",
        "--bucket","openpayments-dezoomcamp2026-us-west-1-1f83ec",
        "--out-root","/app/data/out",
        "--totals-dir","/app/data/totals",
        "--max-files","50",
        "--ensure-totals",
        "--id-workers","10",
        "--page-workers","5",
        "--resume"
      ]
