[project]
name = "data-engineering-zoomcamp"
version = "0.1.0"
description = "Data zoomcamp leaning resources"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3",
    "botocore",
    "pandas",
    "requests",
    "tqdm",
    "click",
    "urllib3"
]